name: Docker Compose Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env.dev
        run: touch .env.dev

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for startup
        run: sleep 10

      - name: Show running containers
        run: docker ps

      - name: Check web container is running
        run: docker ps | grep twitter_final-web

      - name: Stop containers
        run: docker compose down
